# Generated by pyabigen 0.2.0

import typing

import eth_typing
import web3
from web3.contract import contract

__version__ = "v0.14.0"

ADDRESS = typing.cast(
    eth_typing.ChecksumAddress, "0x8Be503bcdEd90ED42Eff31f56199399B2b0154CA"
)


class ACU:
    """ACU contract wrapper."""

    _contract: contract.Contract

    def __init__(
        self,
        w3: web3.Web3,
    ):
        self._contract = w3.eth.contract(
            address=ADDRESS,
            abi=abi,
        )

    def modify_basket(
        self,
        symbols_: typing.List[str],
        quantities_: typing.List[int],
        scale_: int,
    ) -> contract.ContractFunction:
        """See `modifyBasket` on the ACU contract."""
        return self._contract.functions.modifyBasket(
            symbols_,
            quantities_,
            scale_,
        )

    def quantities(
        self,
    ) -> typing.List[int]:
        """See `quantities` on the ACU contract."""
        return_value = self._contract.functions.quantities().call()
        return [int(elem) for elem in return_value]

    def round(
        self,
    ) -> int:
        """See `round` on the ACU contract."""
        return_value = self._contract.functions.round().call()
        return int(return_value)

    def scale(
        self,
    ) -> int:
        """See `scale` on the ACU contract."""
        return_value = self._contract.functions.scale().call()
        return int(return_value)

    def scale_factor(
        self,
    ) -> int:
        """See `scaleFactor` on the ACU contract."""
        return_value = self._contract.functions.scaleFactor().call()
        return int(return_value)

    def symbols(
        self,
    ) -> typing.List[str]:
        """See `symbols` on the ACU contract."""
        return_value = self._contract.functions.symbols().call()
        return [str(elem) for elem in return_value]

    def value(
        self,
    ) -> int:
        """See `value` on the ACU contract."""
        return_value = self._contract.functions.value().call()
        return int(return_value)


abi = [
    {
        "inputs": [
            {"internalType": "string[]", "name": "symbols_", "type": "string[]"},
            {"internalType": "uint256[]", "name": "quantities_", "type": "uint256[]"},
            {"internalType": "uint256", "name": "scale_", "type": "uint256"},
            {"internalType": "address", "name": "autonity", "type": "address"},
            {"internalType": "address", "name": "operator", "type": "address"},
            {"internalType": "address", "name": "oracle", "type": "address"},
        ],
        "stateMutability": "nonpayable",
        "type": "constructor",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": False,
                "internalType": "string[]",
                "name": "symbols",
                "type": "string[]",
            },
            {
                "indexed": False,
                "internalType": "uint256[]",
                "name": "quantities",
                "type": "uint256[]",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "scale",
                "type": "uint256",
            },
        ],
        "name": "BasketModified",
        "type": "event",
    },
    {"inputs": [], "name": "InvalidBasket", "type": "error"},
    {"inputs": [], "name": "NoACUValue", "type": "error"},
    {"inputs": [], "name": "Unauthorized", "type": "error"},
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "height",
                "type": "uint256",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "timestamp",
                "type": "uint256",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "round",
                "type": "uint256",
            },
            {
                "indexed": False,
                "internalType": "int256",
                "name": "value",
                "type": "int256",
            },
        ],
        "name": "Updated",
        "type": "event",
    },
    {
        "inputs": [
            {"internalType": "string[]", "name": "symbols_", "type": "string[]"},
            {"internalType": "uint256[]", "name": "quantities_", "type": "uint256[]"},
            {"internalType": "uint256", "name": "scale_", "type": "uint256"},
        ],
        "name": "modifyBasket",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "quantities",
        "outputs": [{"internalType": "uint256[]", "name": "", "type": "uint256[]"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "round",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "scale",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "scaleFactor",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "address", "name": "operator", "type": "address"}],
        "name": "setOperator",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "address", "name": "oracle", "type": "address"}],
        "name": "setOracle",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "symbols",
        "outputs": [{"internalType": "string[]", "name": "", "type": "string[]"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "update",
        "outputs": [{"internalType": "bool", "name": "status", "type": "bool"}],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "value",
        "outputs": [{"internalType": "int256", "name": "", "type": "int256"}],
        "stateMutability": "view",
        "type": "function",
    },
]
