"""Oracle contract wrapper and data structures."""

# Generated by pyabigen 0.2.4

import typing

import eth_typing
import web3
from web3.contract import base_contract, contract

__version__ = "v0.14.0"


class RoundData(typing.NamedTuple):
    """Port of `struct RoundData` on the IOracle contract."""

    round: int
    price: int
    timestamp: int
    success: bool


class Oracle:
    """Oracle contract wrapper.

    Parameters
    ----------
    w3 : web3.Web3
    address : eth_typing.ChecksumAddress
        The address of a deployed Oracle contract.
    """

    _contract: contract.Contract

    def __init__(
        self,
        w3: web3.Web3,
        address: eth_typing.ChecksumAddress,
    ):
        self._contract = w3.eth.contract(
            address=address,
            abi=ABI,
        )

    @property
    def NewRound(self) -> typing.Type[base_contract.BaseContractEvent]:
        """Wrapper for `event NewRound` on the Oracle contract.

        Emitted when a new voting round is started. round - the new round ID height -
        the height of the current block being executed in the EVM context. timestamp -
        the TS in time's seconds since Jan 1 1970 (Unix time) that the block been mined
        by protocol votePeriod - the round period in blocks for the price voting and
        aggregation.
        """
        return self._contract.events.NewRound

    @property
    def NewSymbols(self) -> typing.Type[base_contract.BaseContractEvent]:
        """Wrapper for `event NewSymbols` on the Oracle contract.

        Emitted when a vote has been succesfully accounted after a {vote} call. round -
        the round at which new symbols are effective
        """
        return self._contract.events.NewSymbols

    @property
    def Voted(self) -> typing.Type[base_contract.BaseContractEvent]:
        """Wrapper for `event Voted` on the Oracle contract.

        Emitted when a vote has been succesfully accounted after a {vote} call.
        """
        return self._contract.events.Voted

    def get_precision(
        self,
    ) -> int:
        """Wrapper for `getPrecision` on the Oracle contract.

        Precision to be used with price reports

        Returns
        -------
        int
        """
        return_value = self._contract.functions.getPrecision().call()
        return int(return_value)

    def get_round(
        self,
    ) -> int:
        """Wrapper for `getRound` on the Oracle contract.

        Retrieve the current round ID.

        Returns
        -------
        int
        """
        return_value = self._contract.functions.getRound().call()
        return int(return_value)

    def get_round_data(
        self,
        _round: int,
        _symbol: str,
    ) -> RoundData:
        """Wrapper for `getRoundData` on the Oracle contract.

        Return price data for a specific round.

        Parameters
        ----------
        _round : int
            , the round for which the price should be returned.
        _symbol : str
            , the symbol for which the current price should be returned.

        Returns
        -------
        RoundData
        """
        return_value = self._contract.functions.getRoundData(
            _round,
            _symbol,
        ).call()
        return RoundData(
            int(return_value[0]),
            int(return_value[1]),
            int(return_value[2]),
            bool(return_value[3]),
        )

    def get_symbols(
        self,
    ) -> typing.List[str]:
        """Wrapper for `getSymbols` on the Oracle contract.

        Retrieve the lists of symbols to be voted on. Need to be called by the Oracle
        Server as part of the init.

        Returns
        -------
        typing.List[str]
        """
        return_value = self._contract.functions.getSymbols().call()
        return [str(elem) for elem in return_value]

    def get_vote_period(
        self,
    ) -> int:
        """Wrapper for `getVotePeriod` on the Oracle contract.

        vote period to be used for price voting and aggregation

        Returns
        -------
        int
        """
        return_value = self._contract.functions.getVotePeriod().call()
        return int(return_value)

    def get_voters(
        self,
    ) -> typing.List[eth_typing.ChecksumAddress]:
        """Wrapper for `getVoters` on the Oracle contract.

        Retrieve the current voters in the committee.

        Returns
        -------
        typing.List[eth_typing.ChecksumAddress]
        """
        return_value = self._contract.functions.getVoters().call()
        return [eth_typing.ChecksumAddress(elem) for elem in return_value]

    def last_round_block(
        self,
    ) -> int:
        """Wrapper for `lastRoundBlock` on the Oracle contract.

        Returns
        -------
        int
        """
        return_value = self._contract.functions.lastRoundBlock().call()
        return int(return_value)

    def last_voter_update_round(
        self,
    ) -> int:
        """Wrapper for `lastVoterUpdateRound` on the Oracle contract.

        Returns
        -------
        int
        """
        return_value = self._contract.functions.lastVoterUpdateRound().call()
        return int(return_value)

    def latest_round_data(
        self,
        _symbol: str,
    ) -> RoundData:
        """Wrapper for `latestRoundData` on the Oracle contract.

        Return latest available price data.

        Parameters
        ----------
        _symbol : str
            , the symbol from which the current price should be returned.

        Returns
        -------
        RoundData
        """
        return_value = self._contract.functions.latestRoundData(
            _symbol,
        ).call()
        return RoundData(
            int(return_value[0]),
            int(return_value[1]),
            int(return_value[2]),
            bool(return_value[3]),
        )

    def new_symbols(
        self,
        key0: int,
    ) -> str:
        """Wrapper for `newSymbols` on the Oracle contract.

        Parameters
        ----------
        key0 : int

        Returns
        -------
        str
        """
        return_value = self._contract.functions.newSymbols(
            key0,
        ).call()
        return str(return_value)

    def reports(
        self,
        key0: str,
        key1: eth_typing.ChecksumAddress,
    ) -> int:
        """Wrapper for `reports` on the Oracle contract.

        Parameters
        ----------
        key0 : str
        key1 : eth_typing.ChecksumAddress

        Returns
        -------
        int
        """
        return_value = self._contract.functions.reports(
            key0,
            key1,
        ).call()
        return int(return_value)

    def round(
        self,
    ) -> int:
        """Wrapper for `round` on the Oracle contract.

        Returns
        -------
        int
        """
        return_value = self._contract.functions.round().call()
        return int(return_value)

    def set_symbols(
        self,
        _symbols: typing.List[str],
    ) -> contract.ContractFunction:
        """Wrapper for `setSymbols` on the Oracle contract.

        Update the symbols to be requested. Only effective at the next round. Restricted
        to the operator account. emit {NewSymbols} event.

        Parameters
        ----------
        _symbols : typing.List[str]

        Returns
        -------
        web3.contract.contract.ContractFunction
            A contract function instance to be sent in a transaction.
        """
        return self._contract.functions.setSymbols(
            _symbols,
        )

    def symbol_updated_round(
        self,
    ) -> int:
        """Wrapper for `symbolUpdatedRound` on the Oracle contract.

        Returns
        -------
        int
        """
        return_value = self._contract.functions.symbolUpdatedRound().call()
        return int(return_value)

    def symbols(
        self,
        key0: int,
    ) -> str:
        """Wrapper for `symbols` on the Oracle contract.

        Parameters
        ----------
        key0 : int

        Returns
        -------
        str
        """
        return_value = self._contract.functions.symbols(
            key0,
        ).call()
        return str(return_value)

    def vote(
        self,
        _commit: int,
        _reports: typing.List[int],
        _salt: int,
    ) -> contract.ContractFunction:
        """Wrapper for `vote` on the Oracle contract.

        Vote for the current period. In order to save gas, if (reports[i] ==
        INVALID_PRICE)g the symbols. if the validator leave consensus committee then his
        vote is discarded. if a validator joins the consensus committee then his first
        vote is not taken into account. Only allowed to vote once per round.

        Parameters
        ----------
        _commit : int
            hash of the new reports        _reports reveal of the reports for the
            previous cycle.        _salt  slat value which was used to generate last
            round commitment
        _reports : typing.List[int]
        _salt : int

        Returns
        -------
        web3.contract.contract.ContractFunction
            A contract function instance to be sent in a transaction.
        """
        return self._contract.functions.vote(
            _commit,
            _reports,
            _salt,
        )

    def vote_period(
        self,
    ) -> int:
        """Wrapper for `votePeriod` on the Oracle contract.

        Returns
        -------
        int
        """
        return_value = self._contract.functions.votePeriod().call()
        return int(return_value)

    def voting_info(
        self,
        key0: eth_typing.ChecksumAddress,
    ) -> typing.Tuple[int, int, bool]:
        """Wrapper for `votingInfo` on the Oracle contract.

        Parameters
        ----------
        key0 : eth_typing.ChecksumAddress

        Returns
        -------
        int
        int
        bool
        """
        return_value = self._contract.functions.votingInfo(
            key0,
        ).call()
        return (
            int(return_value[0]),
            int(return_value[1]),
            bool(return_value[2]),
        )


ABI = [
    {
        "inputs": [
            {"internalType": "address[]", "name": "_voters", "type": "address[]"},
            {"internalType": "address", "name": "_autonity", "type": "address"},
            {"internalType": "address", "name": "_operator", "type": "address"},
            {"internalType": "string[]", "name": "_symbols", "type": "string[]"},
            {"internalType": "uint256", "name": "_votePeriod", "type": "uint256"},
        ],
        "stateMutability": "nonpayable",
        "type": "constructor",
    },
    {"stateMutability": "payable", "type": "fallback"},
    {"stateMutability": "payable", "type": "receive"},
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "_round",
                "type": "uint256",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "_height",
                "type": "uint256",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "_timestamp",
                "type": "uint256",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "_votePeriod",
                "type": "uint256",
            },
        ],
        "name": "NewRound",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": False,
                "internalType": "string[]",
                "name": "_symbols",
                "type": "string[]",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "_round",
                "type": "uint256",
            },
        ],
        "name": "NewSymbols",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": True,
                "internalType": "address",
                "name": "_voter",
                "type": "address",
            },
            {
                "indexed": False,
                "internalType": "int256[]",
                "name": "_votes",
                "type": "int256[]",
            },
        ],
        "name": "Voted",
        "type": "event",
    },
    {
        "inputs": [],
        "name": "finalize",
        "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "getPrecision",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "pure",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "getRound",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "uint256", "name": "_round", "type": "uint256"},
            {"internalType": "string", "name": "_symbol", "type": "string"},
        ],
        "name": "getRoundData",
        "outputs": [
            {
                "components": [
                    {"internalType": "uint256", "name": "round", "type": "uint256"},
                    {"internalType": "int256", "name": "price", "type": "int256"},
                    {"internalType": "uint256", "name": "timestamp", "type": "uint256"},
                    {"internalType": "bool", "name": "success", "type": "bool"},
                ],
                "internalType": "struct IOracle.RoundData",
                "name": "data",
                "type": "tuple",
            }
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "getSymbols",
        "outputs": [{"internalType": "string[]", "name": "", "type": "string[]"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "getVotePeriod",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "getVoters",
        "outputs": [{"internalType": "address[]", "name": "", "type": "address[]"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "lastRoundBlock",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "lastVoterUpdateRound",
        "outputs": [{"internalType": "int256", "name": "", "type": "int256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "string", "name": "_symbol", "type": "string"}],
        "name": "latestRoundData",
        "outputs": [
            {
                "components": [
                    {"internalType": "uint256", "name": "round", "type": "uint256"},
                    {"internalType": "int256", "name": "price", "type": "int256"},
                    {"internalType": "uint256", "name": "timestamp", "type": "uint256"},
                    {"internalType": "bool", "name": "success", "type": "bool"},
                ],
                "internalType": "struct IOracle.RoundData",
                "name": "data",
                "type": "tuple",
            }
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "name": "newSymbols",
        "outputs": [{"internalType": "string", "name": "", "type": "string"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "string", "name": "", "type": "string"},
            {"internalType": "address", "name": "", "type": "address"},
        ],
        "name": "reports",
        "outputs": [{"internalType": "int256", "name": "", "type": "int256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "round",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "address", "name": "_operator", "type": "address"}],
        "name": "setOperator",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "string[]", "name": "_symbols", "type": "string[]"}
        ],
        "name": "setSymbols",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address[]", "name": "_newVoters", "type": "address[]"}
        ],
        "name": "setVoters",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "symbolUpdatedRound",
        "outputs": [{"internalType": "int256", "name": "", "type": "int256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "name": "symbols",
        "outputs": [{"internalType": "string", "name": "", "type": "string"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "uint256", "name": "_commit", "type": "uint256"},
            {"internalType": "int256[]", "name": "_reports", "type": "int256[]"},
            {"internalType": "uint256", "name": "_salt", "type": "uint256"},
        ],
        "name": "vote",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "votePeriod",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "address", "name": "", "type": "address"}],
        "name": "votingInfo",
        "outputs": [
            {"internalType": "uint256", "name": "round", "type": "uint256"},
            {"internalType": "uint256", "name": "commit", "type": "uint256"},
            {"internalType": "bool", "name": "isVoter", "type": "bool"},
        ],
        "stateMutability": "view",
        "type": "function",
    },
]
