# Generated by pyabigen 0.2.1


import eth_typing
import web3
from web3.contract import contract

__version__ = "v0.14.0"


class SupplyControl:
    """SupplyControl contract wrapper."""

    _contract: contract.Contract

    def __init__(
        self,
        w3: web3.Web3,
        address: eth_typing.ChecksumAddress,
    ):
        self._contract = w3.eth.contract(
            address=address,
            abi=abi,
        )

    def available_supply(
        self,
    ) -> int:
        """See `availableSupply` on the SupplyControl contract."""
        return_value = self._contract.functions.availableSupply().call()
        return int(return_value)

    def burn(
        self,
    ) -> contract.ContractFunction:
        """See `burn` on the SupplyControl contract."""
        return self._contract.functions.burn()

    def mint(
        self,
        recipient: eth_typing.ChecksumAddress,
        amount: int,
    ) -> contract.ContractFunction:
        """See `mint` on the SupplyControl contract."""
        return self._contract.functions.mint(
            recipient,
            amount,
        )

    def set_stabilizer(
        self,
        stabilizer_: eth_typing.ChecksumAddress,
    ) -> contract.ContractFunction:
        """See `setStabilizer` on the SupplyControl contract."""
        return self._contract.functions.setStabilizer(
            stabilizer_,
        )

    def stabilizer(
        self,
    ) -> eth_typing.ChecksumAddress:
        """See `stabilizer` on the SupplyControl contract."""
        return_value = self._contract.functions.stabilizer().call()
        return eth_typing.ChecksumAddress(return_value)

    def total_supply(
        self,
    ) -> int:
        """See `totalSupply` on the SupplyControl contract."""
        return_value = self._contract.functions.totalSupply().call()
        return int(return_value)


abi = [
    {
        "inputs": [
            {"internalType": "address", "name": "autonity", "type": "address"},
            {"internalType": "address", "name": "operator", "type": "address"},
            {"internalType": "address", "name": "stabilizer_", "type": "address"},
        ],
        "stateMutability": "payable",
        "type": "constructor",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "amount",
                "type": "uint256",
            }
        ],
        "name": "Burn",
        "type": "event",
    },
    {"inputs": [], "name": "InvalidAmount", "type": "error"},
    {"inputs": [], "name": "InvalidRecipient", "type": "error"},
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": False,
                "internalType": "address",
                "name": "recipient",
                "type": "address",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "amount",
                "type": "uint256",
            },
        ],
        "name": "Mint",
        "type": "event",
    },
    {"inputs": [], "name": "Unauthorized", "type": "error"},
    {"inputs": [], "name": "ZeroValue", "type": "error"},
    {
        "inputs": [],
        "name": "availableSupply",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "burn",
        "outputs": [],
        "stateMutability": "payable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "recipient", "type": "address"},
            {"internalType": "uint256", "name": "amount", "type": "uint256"},
        ],
        "name": "mint",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "address", "name": "operator", "type": "address"}],
        "name": "setOperator",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "stabilizer_", "type": "address"}
        ],
        "name": "setStabilizer",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "stabilizer",
        "outputs": [{"internalType": "address", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "totalSupply",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
]
