# Build actions for every push
name: onpush

on:
  push:

jobs:
  check:
    strategy:
      matrix:
        python-ver: ['3.8', '3.9', '3.10', '3.11' ]
        os: [ubuntu-22.04, macos-latest]

    runs-on: ${{matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-ver }}
    - name: Install Hatch
      run: pip install --upgrade hatch
    - name: Lint
      run: make lint
    - name: Test
      run: make test

