# Build actions for every push
name: onpush

on:
  push:

jobs:
  check:
    strategy:
      matrix:
        python-ver: ['3.8', '3.9', '3.10', '3.11' ]
        os: [ubuntu-22.04, macos-10.15]

    runs-on: ${{matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-ver }}
    - name: Install and check
      run: |
        python -m venv env
        . env/bin/activate
        make install
        make check
